Repository brenotainandev/animacoes-matriz-leds, pull requests merged in 2025-01, with the labels that each got.

#1 Monatagem do circuito, configuração dos pinos e leitura do teclado
  animacoes-matriz-leds.c
  diagram.json
  wokwi.toml
Labels: enhancement

#9 Nova funcionalidade para a tecla D
  animacoes-matriz-leds.c
Labels: bug, enhancement

#15 Update README.md
  README.md
Labels: documentation

#12 Feature Duda animacao
  animacoes-matriz-leds.c
Labels: bug, enhancement

#14 Feat/animacao 4 c
  animacoes-matriz-leds.c
Labels: enhancement

#17 Funcionalidade da tecla 5
  animacoes-matriz-leds.c
Labels: enhancement

#18 Organização de código
  .vscode/settings.json
  CMakeLists.txt
  animacoes-matriz-leds.c
  includes/animacoes.h
  includes/buzzer.h
  includes/matriz-led.h
  includes/modo-gravacao.h
  includes/teclado.h
  src/animacoes.c
  src/buzzer.c
  src/matriz-led.c
  src/modo-gravacao.c
  src/teclado.c
Labels: documentation, enhancement

#22 atualizacao animacao 6
  src/animacoes.c
Labels: enhancement
